### PR TITLE
add @AntiCommandBot powered by @GroupOwnerBots

### PR DESCRIPTION
**Pull request by SpEcHiDe**
Adding this to the NO_LOAD will disable this module. 

created because [@AntiCommandBot](https://telegram.dog/AntiCommandBot) is down for unknown reasons.

### CODE REVIEW

**Comment by varunhardgamer** [comment]
DEL_CMDS is there for a reason, lol

**Comment by SpEcHiDe** [comment]
that won't delete the "blue text" commands that are not part of the CommandHandler

**Comment by varunhardgamer** [comment]
:D then extend your "command handler"

**Comment by Yasir-siddiqui** [comment]
Still waiting when you will upgrade it I need function to on/off

**Pull request closed without merging**
